### ISSUE TITLE
Website Not showing right

### ISSUE THREAD

**Issue by xhendrikg** [Gamemode4Dev/gm4.co#7]
**Describe the bug**

**To Reproduce**
1. https://gm4.co/modules/beehive-inspector

iPhone 7 Safari

**Expected behavior**
Describe what you expected to happen.

**Fix**
Outline how this bug could be fixed.

**Screenshots**
If applicable, add screenshots to help others understand your problem.

**Environment**
 - Minecraft version:
 - Server version:
 - Installed Datapacks:
 - Installed Mods:

**Additional context**

**Comment by sparks0** [comment]
Thank you for the report but this isn't enough information for us to solve the issue. Please include some screenshots or a description of HOW the web page is not displaying right.

**Comment by sparks0** [comment]
This issue has been resolved.
